PREFIX = 'resolve_'
POST_PREFIX = 'post_'
RESOLVER = 'RESOLVER'
ATTRIBUTE = 'ATTRIBUTE'
PYDANTIC_FORWARD_REF_UPDATED = '__pydantic_resolve_forward_refs_updated__'
HAS_MAPPER_FUNCTION = '__pydantic_resolve_mapper_provided__'